language: c

os:
  - linux
  
before_install:
  - export TI_PRU_CGT_VERSION="2.2.1"
  - export TI_PRU_CGT_DST="ti-pru-cgt"
  - export ROOT_DIR=${PWD}
  - export DL_DIR="download"
  - mkdir download
  - cd ${ROOT_DIR}/${DL_DIR}/ && mkdir pru_cgt_installer
  - wget -O http://software-dl.ti.com/codegen/esd/cgt_public_sw/PRU/${TI_PRU_CGT_VERSION}/ti_cgt_pru_${TI_PRU_CGT_VERSION}_linux_installer_x86.bin

  - wget -c https://releases.linaro.org/components/toolchain/binaries/7.4-2019.02/arm-linux-gnueabihf/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf.tar.xz
  - tar xf gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf.tar.xz
  - export PATH=$PATH:$PWD/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf/bin/
  - arm-linux-gnueabihf-gcc --version

before_script:
  - chmod +x ${ROOT_DIR}/${DL_DIR}/pru_cgt_installer
  - pru_cgt_installer <<<${TI_PRU_CGT_DST}
  

script:

  # exporting the variable to be used by make utility  
  - export ARCH=arm 
  - export CROSS_COMPILE=arm-linux-gnueabihf-
  - make
